baseurl             = "http://michaelhealy.space"
DefaultContentLanguage = "en"
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
theme               = "beautifulhugo"
author              = "Michael Healy"
title               = "Michael Healy"
pygmentsUseClasses  = true
pygmentCodeFences = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
#googleAnalytics     = "UA-123-45"


[[menu.main]]
name                   = "Blog"
weight                 = -130
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Recipes"
weight                 = -120
identifier             = "recipes"
url                    = "/recipes/"

[[menu.main]]
name = "Compositions"
weight = -110
identifier = "compositions"
url = "/compositions/"

[[menu.main]]
name = "CV and Academics"
weight = -105
identifier = "academics"
url = "http://michaelhealy.space/academic/"

[[menu.main]]
name = "About Me"
weight = -100
identifier = "about"
url = "/about/"

[params]
dateFormat = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
subtitle = "Personal blog about adventures in academia, running, and the kitchen"
logo = "img/runner.png"
favicon = "img/runner.png"
rss = true

[Author]
github = "mjh16"
Name = "Michael Healy"
email = "mhealy2011@gmail.com"
twitter = "mhealy_rhet"
instagram = "mjhealy"
posts_navigation = true
#linkedin               = "//linkedin.com/in/you"
selfintro              = "Runner, Rhetoric and Composition Student, Homebrewer, wannabe Bread Baker, Cook, and Sometimes Gamer"
avatar                 = "img/IMG_0665.jpg"

[taxonomies]
genre = "genres"
series = "series"
meal = "meals"
category = "categories"
tag = "tags"
