baseurl             = "http://michaelhealy.space/"
DefaultContentLanguage = "en"
theme               = "beautifulhugo"
author              = "Michael Healy"
title               = "Michael Healy"
metaDataFormat = "toml"
pygmentCodeFences = false
pygmentsUseClasses = false
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
#googleAnalytics     = "UA-123-45"

[[menu.main]]
name                   = "Blog"
weight                 = -130
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Recipes"
weight                 = -120
identifier             = "recipes"
url                    = "/recipes/"

[[menu.main]]
name = "Compositions"
weight = -110
identifier = "compositions"
url = "/compositions/"

[[menu.main]]
name = "Academics"
weight = -105
identifier = "academics"
url = "http://michaelhealy.space/academic/"

[[menu.main]]
name = "About Me"
weight = -100
identifier = "about"
url = "/about/"

[params]
  subtitle = "Adventures in academia, on the trail, and in the kitchen."
  logo = "img/runner.png"
  favicon = "img/runnerico.png"
  dateFormat = "Jan 2, 2006"
  rss = true
  comments = true
  commit = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
name = "Michael Healy"
email = "mhealy2011@gmail.com"
github = "mjh16"
twitter = "mhealy_rhet"
instagram = "mjhealy"
spotify = "crispy2011"
linkedin = "mjh16"


#[[Params.bigimg]]
#  src = "img/cover3.jpg"
#  desc = "Lake Bradford"
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[taxonomies]
series = "series"
meal = "meals"
category = "categories"
tag = "tags"
composition = "compositions"
