baseurl             = "http://michaelhealy.space/"
DefaultContentLanguage = "en"
languageCode        = "en-US"
theme               = "cocoa"
author              = "Michael Healy"
title               = "Michael Healy"
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
#googleAnalytics     = "UA-123-45"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -130
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Recipes"
weight                 = -120
identifier             = "recipes"
url                    = "/recipes/"

[[menu.main]]
name = "Compositions"
weight = -110
identifier = "compositions"
url = "/compositions/"

[[menu.main]]
name = "Academics"
weight = -105
identifier = "academics"
url = "http://michaelhealy.space/academic/"

[[menu.main]]
name = "About Me"
weight = -100
identifier = "about"
url = "/about/"

[params]
latestpostscount = 5
author = "Michael Healy"
dateform = "Jan 2, 2006"
cachebuster = true
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Adventures in academia, running, and the kitchen"
email = "mhealy2011@gmail.com"
github = "//github.com/mjh16"
highlightjs = false
lang = "en"
noshowreadtime = false
selfintro = "Adventures in academia, running, and the kitchen"
twitter = "//twitter.com/mhealy_rhet"
avatar = "img/runner.png"
instagram = "//instagram.com/mjhealy"

[taxonomies]
series = "series"
meal = "meals"
category = "categories"
tag = "tags"
composition = "compositions"
